version: '3.7'

services:
  account:
    build: ./services/account/
    image: docker.pkg.github.com/ajithpmohan/social-media-app/account:1.0
    container_name: account
    volumes:
      - ./services/account:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5000:5000"
    # Port 9229 is the default NodeJS debugging port.
    expose:
      - 9229
  feed:
    build: ./services/feed/
    image: docker.pkg.github.com/ajithpmohan/social-media-app/feed:1.0
    container_name: feed
    volumes:
      - ./services/feed:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5001:5000"
    # Port 9229 is the default NodeJS debugging port.
    expose:
      - 9229
  gateway:
    build: ./services/gateway/
    image: docker.pkg.github.com/ajithpmohan/social-media-app/gateway:1.0
    container_name: gateway
    restart: always
    volumes:
      - ./services/gateway:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5002:5000"
    # Port 9229 is the default NodeJS debugging port.
    expose:
      - 9229
  web:
    build: ./services/web/
    image: docker.pkg.github.com/ajithpmohan/social-media-app/web:1.0
    container_name: web
    volumes:
      - ./services/web:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - "5003:5000"
